"""Add created_at column to crop table

Revision ID: 2ffdbef96a44
Revises: a89f8a35cafe
Create Date: 2025-04-13 20:47:02.502231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffdbef96a44'
down_revision = 'a89f8a35cafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
