"""empty message

Revision ID: 746e0d79fc11
Revises: c857f0bc66ef
Create Date: 2025-04-22 18:55:42.909974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746e0d79fc11'
down_revision = 'c857f0bc66ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_forecast')
    op.drop_table('crop_prediction')
    with op.batch_alter_table('crop', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('crop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    op.create_table('crop_prediction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('crop_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('predicted_yield', sa.FLOAT(), nullable=False),
    sa.Column('soil_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('weather_conditions', sa.VARCHAR(length=200), nullable=False),
    sa.Column('prediction_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_forecast',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), nullable=False),
    sa.Column('temperature', sa.FLOAT(), nullable=False),
    sa.Column('humidity', sa.FLOAT(), nullable=False),
    sa.Column('forecast_date', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
